project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - protocol.qmd
    - protocol/changes.qmd
    - protocol/preface.qmd
    - protocol/part1-overview.qmd
    - protocol/part2-workflow.qmd
    - protocol/part3-filenames.qmd
    - protocol/part4-metadata.qmd
    - protocol/part5-instrumentation.qmd
    - protocol/part6-guidelines.qmd
    - protocol/references.qmd
    - protocol/appendix1.qmd
    - protocol/appendix2.qmd
    - protocol/tables.qmd
    - publications.qmd
    - contact.qmd
    # NOTE: intentionally omit protocol/index.qmd

website:
  title: "IHerbSpec"
  site-url: https://iherbspec.github.io
  favicon: images/IHerbSpecIcon-white-bgb.png
  image: images/NaturaSpec-IMG_4840.png
  navbar:
    left:
      - text: "![](images/IHerbSpecIcon-white-bgb.png)"
        href: index.qmd
      - text: IHerbSpec Protocol
        menu:
          - text: Home - IHerbSpec Protocol
            href: protocol.qmd
          - text: Preface
            href: protocol/preface.qmd
          - text: Changes Since Last Version
            href: protocol/changes.qmd  
          - text: Part 1 – Overview
            href: protocol/part1-overview.qmd
          - text: Part 2 – Workflow
            href: protocol/part2-workflow.qmd
          - text: Part 3 – Filenames
            href: protocol/part3-filenames.qmd
          - text: Part 4 – Metadata
            href: protocol/part4-metadata.qmd
          - text: Part 5 – Instrumentation
            href: protocol/part5-instrumentation.qmd
          - text: Part 6 – Tissue Selection
            href: protocol/part6-guidelines.qmd
          - text: References
            href: protocol/references.qmd
          - text: Appendix I
            href: protocol/appendix1.qmd
          - text: Appendix II
            href: protocol/appendix2.qmd
          - text: Downloads
            href: protocol/tables.qmd  
      - text: Publications
        href: publications.qmd
      - text: Contact Us
        href: contact.qmd

format:
  html:
    theme: default
    toc: true
    css: styles.css
    include-in-header: meta.html 

metadata:
  og:image: images/IHerbSpecLogo-white-bgb.png
  og:title: "IHerbSpec"
  og:description: "An international working group developing standards and tools for herbarium spectral digitization."
  twitter:card: summary_large_image
  twitter:image: images/IHerbSpecLogo-white-bgb.png
  twitter:title: "IHerbSpec"
  twitter:description: "International working group advancing standards for herbarium spectral digitization."
  
crossref:
  fig-title: ""
  
execute:
  freeze: true

